famous_people = [
    {"name": "Cristiano Ronaldo", "follower": 630_000_000, "description": "Professional football player", "country": "Portugal"},
    {"name": "Lionel Messi", "follower": 520_000_000, "description": "Professional football player", "country": "Argentina"},
    {"name": "Selena Gomez", "follower": 430_000_000, "description": "Singer and actress", "country": "United States"},
    {"name": "Kylie Jenner", "follower": 420_000_000, "description": "Entrepreneur and influencer", "country": "United States"},
    {"name": "Dwayne Johnson", "follower": 410_000_000, "description": "Actor and former wrestler", "country": "United States"},
    {"name": "Ariana Grande", "follower": 390_000_000, "description": "Singer and actress", "country": "United States"},
    {"name": "Kim Kardashian", "follower": 380_000_000, "description": "Socialite and entrepreneur", "country": "United States"},
    {"name": "Beyoncé", "follower": 320_000_000, "description": "Singer and performer", "country": "United States"},
    {"name": "Neymar Jr.", "follower": 315_000_000, "description": "Professional football player", "country": "Brazil"},
    {"name": "Taylor Swift", "follower": 310_000_000, "description": "Singer and songwriter", "country": "United States"},
    {"name": "Kendall Jenner", "follower": 295_000_000, "description": "Model and influencer", "country": "United States"},
    {"name": "Justin Bieber", "follower": 290_000_000, "description": "Singer", "country": "Canada"},
    {"name": "Khloé Kardashian", "follower": 280_000_000, "description": "Socialite and entrepreneur", "country": "United States"},
    {"name": "Jennifer Lopez", "follower": 270_000_000, "description": "Singer and actress", "country": "United States"},
    {"name": "Virat Kohli", "follower": 265_000_000, "description": "Cricketer", "country": "India"},
    {"name": "Nicki Minaj", "follower": 250_000_000, "description": "Rapper and singer", "country": "United States"},
    {"name": "Miley Cyrus", "follower": 245_000_000, "description": "Singer and actress", "country": "United States"},
    {"name": "Kourtney Kardashian", "follower": 240_000_000, "description": "Socialite and entrepreneur", "country": "United States"},
    {"name": "Zendaya", "follower": 235_000_000, "description": "Actress and singer", "country": "United States"},
    {"name": "Katy Perry", "follower": 230_000_000, "description": "Singer", "country": "United States"},
    {"name": "Rihanna", "follower": 225_000_000, "description": "Singer and entrepreneur", "country": "Barbados"},
    {"name": "LeBron James", "follower": 220_000_000, "description": "Basketball player", "country": "United States"},
    {"name": "Shakira", "follower": 215_000_000, "description": "Singer and dancer", "country": "Colombia"},
    {"name": "Drake", "follower": 210_000_000, "description": "Rapper", "country": "Canada"},
    {"name": "Billie Eilish", "follower": 205_000_000, "description": "Singer", "country": "United States"},
    {"name": "David Beckham", "follower": 200_000_000, "description": "Former football player", "country": "United Kingdom"},
    {"name": "Emma Watson", "follower": 195_000_000, "description": "Actress and activist", "country": "United Kingdom"},
    {"name": "Gigi Hadid", "follower": 190_000_000, "description": "Model", "country": "United States"},
    {"name": "Zlatan Ibrahimović", "follower": 185_000_000, "description": "Football player", "country": "Sweden"},
    {"name": "Shawn Mendes", "follower": 180_000_000, "description": "Singer", "country": "Canada"},
    {"name": "Camila Cabello", "follower": 175_000_000, "description": "Singer", "country": "United States/Cuba"},
    {"name": "Chris Hemsworth", "follower": 170_000_000, "description": "Actor", "country": "Australia"},
    {"name": "Will Smith", "follower": 165_000_000, "description": "Actor", "country": "United States"},
    {"name": "Vin Diesel", "follower": 160_000_000, "description": "Actor", "country": "United States"},
    {"name": "Bad Bunny", "follower": 155_000_000, "description": "Singer", "country": "Puerto Rico"},
    {"name": "Gal Gadot", "follower": 150_000_000, "description": "Actress", "country": "Israel"},
    {"name": "Cardi B", "follower": 145_000_000, "description": "Rapper", "country": "United States"},
    {"name": "Luis Suárez", "follower": 140_000_000, "description": "Football player", "country": "Uruguay"},
    {"name": "Emma Stone", "follower": 135_000_000, "description": "Actress", "country": "United States"},
    {"name": "Robert Downey Jr.", "follower": 130_000_000, "description": "Actor", "country": "United States"},
    {"name": "Chris Evans", "follower": 125_000_000, "description": "Actor", "country": "United States"},
    {"name": "Harry Styles", "follower": 120_000_000, "description": "Singer and actor", "country": "United Kingdom"},
    {"name": "Millie Bobby Brown", "follower": 115_000_000, "description": "Actress", "country": "United Kingdom"},
    {"name": "Jisoo", "follower": 110_000_000, "description": "Singer (BLACKPINK)", "country": "South Korea"},
    {"name": "Lisa", "follower": 105_000_000, "description": "Singer (BLACKPINK)", "country": "Thailand"},
    {"name": "Rosé", "follower": 100_000_000, "description": "Singer (BLACKPINK)", "country": "New Zealand/South Korea"},
    {"name": "Jennie", "follower": 95_000_000, "description": "Singer (BLACKPINK)", "country": "South Korea"},
    {"name": "Anitta", "follower": 85_000_000, "description": "Singer", "country": "Brazil"},
    {"name": "Ivete Sangalo", "follower": 30_000_000, "description": "Singer", "country": "Brazil"}
]
